# Generated by Django 3.0 on 2020-05-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsc',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subsc',
            name='url',
        ),
        migrations.RemoveField(
            model_name='subsc',
            name='validation',
        ),
    ]
