# Generated by Django 3.0 on 2020-05-28 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscapp', '0002_auto_20200528_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsc',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subsc',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsc',
            name='validation',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
