# Generated by Django 3.0 on 2020-05-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscapp', '0003_auto_20200528_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsc',
            name='validation',
        ),
    ]
