# Generated by Django 3.0 on 2020-05-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscapp', '0006_subsc_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsc',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Book', 'Book'), ('Movie', 'Movie'), ('Morter', 'Morter'), ('Others', 'Others')], default='Music', max_length=100),
        ),
    ]
