# Generated by Django 3.0.5 on 2020-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscapp', '0007_subsc_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsc',
            name='dateleft',
            field=models.IntegerField(default=0),
        ),
    ]
